"""empty message

Revision ID: 702effc641f6
Revises: 4932a9c67939
Create Date: 2025-10-07 22:27:37.503503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '702effc641f6'
down_revision = '4932a9c67939'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        # Agregar columna como nullable primero
        batch_op.add_column(
            sa.Column('status', sa.String(length=20), nullable=True))

    # Actualizar valores existentes a 'pending'
    op.execute("UPDATE \"order\" SET status = 'pending' WHERE status IS NULL")

    # Ahora hacer la columna NOT NULL
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('status', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
